
som240_1_pins = {

	'A1'			: 'VCC_BATT',
	'A2'			: 'GND',
        'A3'			: { 'net' : 'HPA06_P', 'dest' : [ 'mipi_csi_ias_data_rxp[0]' ], 'func' : 'ias1', 'io':'LVCMOS18', 'pin':'A2' },
        'A4'			: { 'net' : 'HPA06_N', 'dest' : [ 'mipi_csi_ias_data_rxn[0]' ], 'func' : 'ias1', 'io':'LVCMOS18', 'pin':'A1' },
	'A5'			: 'GND',
        'A6'			: { 'net' : 'HPA_CLK0_P', 'dest' : [ ], 'func' : 'nc', 'pin':'C3' },
        'A7'			: { 'net' : 'HPA_CLK0_P', 'dest' : [ ], 'func' : 'nc', 'pin':'C2' },
	'A8'			: 'GND',
        'A9'			: { 'net' : 'HPA12_P', 'dest' : [ 'rpi_data_rxp[1]' ], 'func' : 'rpi', 'io':'LVCMOS18', 'pin':'G6' },
        'A10'			: { 'net' : 'HPA12_N', 'dest' : [ 'rpi_data_rxn[1]' ], 'func' : 'rpi', 'io':'LVCMOS18', 'pin':'F6' },
	'A11'			: 'GND',
        'A12'			: { 'net' : 'HPA13_P', 'dest' : [  ], 'func' : 'nc', 'pin':'G8' },
        'A13'			: { 'net' : 'HPA13_N', 'dest' : [  ], 'func' : 'nc', 'pin':'F7' },
	'A14'			: 'GND',
        'A15'			: { 'net' : 'HDA09', 'dest' : [ 'slg7x44677_hdio_rpi' ], 'cmt': 'reset controller?', 'io':'LVCMOS33', 'pin':'F11'  },
        'A16'			: { 'net' : 'HDA10', 'dest' : [ 'rpi_12' ], 'func' : 'rpi', 'pin':'J12' },
        'A17'			: { 'net' : 'HDA11', 'dest' : [ 'pmod_1' ], 'v':3.3, 'func': 'pmod', 'io':'LVCMOS33', 'pin':'H12' },
	'A18'			: 'GND',
	'A19'			: { 'net' : 'VCCOEN_PS_M2C', 'dest' : [  ], 'cmt' : 'PS_1V2, PS_1V8, and PS_3V3 regulator enable.' },
	'A20'			: { 'net' : 'VCCOEN_PL_M2C', 'dest' : [  ], 'cmt' : 'PL_1V2, PL_1V8, and PL_3V3 regulator enable.' },
	'A21'			: 'GND',
        'A22'			: { 'net' : 'JTAG_TMS_C2M', 'dest' : [ 'ftdi_tms', 'j3_tms' ], 'v': 1.8, 'cmt' : '', 'func': 'jtag' },
        'A23'			: { 'net' : 'JTAG_TDO_M2C', 'dest' : [ 'ftdi_tdo', 'j3_tdo' ], 'v': 1.8, 'cmt' : '', 'func': 'jtag' },
        'A24'			: { 'net' : 'JTAG_TDI_C2M', 'dest' : [ 'ftdi_tdi', 'j3_tdi' ], 'v': 1.8, 'cmt' : '', 'func': 'jtag' },
        'A25'			: { 'net' : 'JTAG_TCK_C2M', 'dest' : [ 'ftdi_tck', 'j3_tck' ], 'v': 1.8, 'cmt' : '', 'func': 'jtag' },
	'A26'			: 'GND',
	'A27'			: { 'net' : 'MODE0_C2M', 'dest' : [ 'GND' ], 'cmt' : '' },
	'A28'			: { 'net' : 'MODE1_C2M', 'dest' : [ ], 'cmt' : 'Probably a pullup on the module' },
	'A29'			: { 'net' : 'MODE2_C2M', 'dest' : [ 'GND' ], 'cmt' : '' },
	'A30'			: { 'net' : 'MODE3_C2M', 'dest' : [ 'GND' ], 'cmt' : '' },
        'A31'			: { 'net' : 'MIO32', 'dest' : [  ], 'cmt' : '', 'func' : 'nc' },
        'A32'			: { 'net' : 'MIO33', 'dest' : [  ], 'cmt' : '', 'func' : 'nc' },
	'A33'			: 'GND',
        'A34'			: { 'net' : 'MIO41', 'dest' : [  ], 'cmt' : '', 'func' : 'nc' },
        'A35'			: { 'net' : 'MIO42', 'dest' : [  ], 'cmt' : '', 'func' : 'nc' },
	'A36'			: { 'net' : 'MIO43', 'dest' : [ 'slg7x44677_ps_mio_sd' ], 'cmt' : '' },
	'A37'			: 'GND',
        'A38'			: { 'net' : 'MIO61', 'dest' : [ 'ulpi_data5' ], 'v': 1.8, 'cmt' : '', 'func':'ulpi' },
        'A39'			: { 'net' : 'MIO62', 'dest' : [ 'ulpi_data6' ], 'v': 1.8, 'cmt' : '', 'func':'ulpi' },
        'A40'			: { 'net' : 'MIO63', 'dest' : [ 'ulpi_data7' ], 'v': 1.8, 'cmt' : '', 'func':'ulpi' },
	'A41'			: 'GND',
        'A42'			: { 'net' : 'MIO73', 'dest' : [ 'eth_rx_d2' ], 'v': 1.8 , 'cmt' : '', 'func':'eth' },
        'A43'			: { 'net' : 'MIO74', 'dest' : [ 'eth_rx_d3' ], 'v': 1.8 , 'cmt' : '', 'func':'eth' },
        'A44'			: { 'net' : 'MIO75', 'dest' : [ 'eth_rx_ctrl' ], 'v': 1.8 , 'cmt' : '', 'func':'eth' },
	'A45'			: 'GND',
	'A46'			: 'GND',
	'A47'			: { 'net' : 'GTR_DP1_M2C_P', 'dest' : [ 'stdp4320_rx0_ln0_p' ], 'cmt' : 'DP out' },
	'A48'			: { 'net' : 'GTR_DP1_M2C_N', 'dest' : [ 'stdp4320_rx0_ln0_n' ], 'cmt' : 'DP out' },
	'A49'			: 'GND',
	'A50'			: 'GND',
        'A51'			: { 'net' : 'GTR_REFCLK3_C2M_P', 'dest' : [ '' ], 'cmt' : '', 'func' : 'nc' },
        'A52'			: { 'net' : 'GTR_REFCLK3_C2M_N', 'dest' : [ '' ], 'cmt' : '', 'func' : 'nc' },
	'A53'			: 'GND',
	'A54'			: 'GND',
        'A55'			: { 'net' : 'GTR_DP0_C2M_P', 'dest' : [ '' ], 'cmt' : 'DP in ', 'func' : 'nc' },
        'A56'			: { 'net' : 'GTR_DP0_C2M_N', 'dest' : [ '' ], 'cmt' : 'DP in ', 'func' : 'nc' },
	'A57'			: 'GND',
	'A58'			: 'GND',
	'A59'			: 'SOM_5V0',
	'A60'			: 'SOM_5V0',

        'B1'			:  { 'net' : 'HPA05_CC_P', 'dest' : [ 'mipi_csi_ias_clk_rxp' ], 'cmt' : '', 'func' : 'ias1', 'io':'LVCMOS18', 'pin':'C1' },
        'B2'			:  { 'net' : 'HPA05_CC_N', 'dest' : [ 'mipi_csi_ias_clk_rxn' ], 'cmt' : '', 'func' : 'ias1', 'io':'LVCMOS18', 'pin':'B1' },
	'B3'			: 'GND',
        'B4'			:  { 'net' : 'HPA04_P', 'dest' : [ 'mipi_csi_isp_data_rxp[3]' ], 'cmt' : '', 'io':'LVCMOS18', 'func':'isp' },
        'B5'			:  { 'net' : 'HPA04_N', 'dest' : [ 'mipi_csi_isp_data_rxn[3]' ], 'cmt' : '', 'io':'LVCMOS18', 'func':'isp', 'pin':'E3' },
	'B6'			: 'GND',
        'B7'			:  { 'net' : 'HPA07_P', 'dest' : [ 'mipi_csi_ias_data_rxp[1]' ], 'cmt' : '', 'func' : 'ias1', 'io':'LVCMOS18', 'pin':'B3' },
        'B8'			:  { 'net' : 'HPA07_N', 'dest' : [ 'mipi_csi_ias_data_rxn[1]' ], 'cmt' : '', 'func' : 'ias1', 'io':'LVCMOS18', 'pin':'A3' },
	'B9'			: 'GND',
        'B10'			:  { 'net' : 'HPA11_P', 'dest' : [ 'rpi_data_rxp[0]' ], 'cmt' : '', 'func' : 'rpi', 'io':'LVCMOS18', 'pin':'E5' },
        'B11'			:  { 'net' : 'HPA11_N', 'dest' : [ 'rpi_data_rxn[0]' ], 'cmt' : '', 'func' : 'rpi', 'io':'LVCMOS18', 'pin':'D5' },
	'B12'			: 'GND',
	'B13'			: 'PL_3V3',
	'B14'			: 'PL_3V3',
	'B15'			: 'GND',
        'B16'			:  { 'net' : 'HDA03', 'dest' : [ 'ap1302_standby' ], 'cmt' : '', 'pin': 'J10', 'io': 'LVCMOS33', 'v': 3.3, 'func':'isp', 'pin':'J10'},
        'B17'			:  { 'net' : 'HDA04', 'dest' : [ 'slg7xl44677_hdio_direct' ], 'cmt' : '', 'io':'LVCMOS33', 'pin':'K13' },
        'B18'			:  { 'net' : 'HDA05', 'dest' : [ '' ], 'cmt' : '', 'func' : 'nc', 'pin':'K12' },
	'B19'			: 'GND',
        'B20'			:  { 'net' : 'HDA15', 'dest' : [ 'pmod_2' ], 'v':3.3, 'cmt' : '', 'func': 'pmod', 'io':'LVCMOS33', 'pin':'B10' },
        'B21'			:  { 'net' : 'HDA16_CC', 'dest' : [ 'pmod_4' ], 'v':3.3, 'cmt' : '', 'func': 'pmod', 'io':'LVCMOS33', 'pin':'E12' },
        'B22'			:  { 'net' : 'HDA17', 'dest' : [ 'pmod_6' ], 'v':3.3, 'cmt' : '', 'func': 'pmod', 'io':'LVCMOS33', 'pin':'D11' },
	'B23'			: 'GND',
	'B24'			:  { 'net' : 'PS_ERROR_OUT_M2C', 'dest' : [ 'tp38' ], 'cmt' : '' },
	'B25'			:  { 'net' : 'PS_ERROR_STATUS_M2C', 'dest' : [ 'tp39' ], 'cmt' : '' },
	'B26'			:  { 'net' : 'PWROFF_C2M_B', 'dest' : [ '' ], 'cmt' : 'comes from 12DC barrel jack plug detect, goes to regulators Power Good' },
	'B27'			: 'GND',
	'B28'			: { 'net' : 'MIO35', 'dest' : [ 'wdog_wdi' ], 'v': 1.8, 'cmt' : '' },
	'B29'			: { 'net' : 'MIO36', 'dest' : [ 'som_uart1_txd' ], 'v': 1.8, 'cmt' : '' },
	'B30'			: { 'net' : 'MIO37', 'dest' : [ 'som_uart2_rxd' ], 'v': 1.8, 'cmt' : '' },
	'B31'			: 'GND',
	'B32'			: { 'net' : 'MIO38', 'dest' : [ 'slg7xl44677_ps_mio_eth' ], 'v': 1.8, 'cmt' : '' },
        'B33'			: { 'net' : 'MIO39', 'dest' : [ 'sdio_sel' ], 'v': 1.8, 'cmt' : 'activates level shifter pi4uls3v4857', 'func':'sdio' },
        'B34'			: { 'net' : 'MIO40', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '', 'func' : 'nc' },
	'B35'			: 'GND',
        'B36'			: { 'net' : 'MIO50', 'dest' : [ 'sdio_cmd' ], 'v': 1.8, 'cmt' : '', 'func':'sdio' },
        'B37'			: { 'net' : 'MIO51', 'dest' : [ 'sdio_clk' ], 'v': 1.8, 'cmt' : '', 'func':'sdio' },
        'B38'			: { 'net' : 'MIO34', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '', 'func' : 'nc' },
	'B39'			: 'GND',
        'B40'			: { 'net' : 'MIO58', 'dest' : [ 'ulpi_stp' ], 'v': 1.8, 'cmt' : '', 'func':'ulpi' },
        'B41'			: { 'net' : 'MIO59', 'dest' : [ 'ulpi_data3' ], 'v': 1.8, 'cmt' : '', 'func':'ulpi' },
        'B42'			: { 'net' : 'MIO60', 'dest' : [ 'ulpi_data4' ], 'v': 1.8, 'cmt' : '', 'func':'ulpi' },
	'B43'			: 'GND',
        'B44'			: { 'net' : 'MIO70', 'dest' : [ 'eth_rx_clk' ], 'v': 1.8, 'cmt' : '', 'func':'eth' },
        'B45'			: { 'net' : 'MIO71', 'dest' : [ 'eth_rx_d0' ], 'v': 1.8, 'cmt' : '', 'func':'eth' },
        'B46'			: { 'net' : 'MIO72', 'dest' : [ 'eth_rx_d1' ], 'v': 1.8, 'cmt' : '', 'func':'eth' },
	'B47'			: 'GND',
	'B48'			: 'GND',
	'B49'			: { 'net' : 'GTR_REFCLK1_C2M_P', 'dest' : [ 'clkgen_out4' ], 'cmt' : 'Si5332 - 26MHz - Used by PS' },
	'B50'			: { 'net' : 'GTR_REFCLK1_C2M_N', 'dest' : [ 'clkgen_out4b' ], 'cmt' : 'Si5332 - 26MHz - Used by PS' },
	'B51'			: 'GND',
	'B52'			: 'GND',
	'B53'			: { 'net' : 'GTR_DP2_C2M_P', 'dest' : [ 'usb5744_usb3up_txdp' ], 'cmt' : 'upstream facing usb3 port of hub' },
	'B54'			: { 'net' : 'GTR_DP2_C2M_N', 'dest' : [ 'usb5744_usb3up_txdm' ], 'cmt' : 'upstream facing usb3 port of hub' },
	'B55'			: 'GND',
	'B56'			: 'GND',
	'B57'			: { 'net' : 'GTR_DP0_M2C_P', 'dest' : [ 'stdp4320_rx0_ln1_p' ], 'cmt' : '' },
	'B58'			: { 'net' : 'GTR_DP0_M2C_N', 'dest' : [ 'stdp4320_rx0_ln1_n' ], 'cmt' : '' },
	'B59'			: 'GND',
	'B60'			: 'SOM_5V0',

	'C1'			: 'GND',
	'C2'			: 'GND',
        'C3'			: { 'net' : 'HPA00_CC_P', 'dest' : [ 'mipi_csi_isp_clk_rxp' ], 'cmt' : '', 'io':'LVCMOS18', 'func':'isp', 'pin':'G1' },
        'C4'			: { 'net' : 'HPA00_CC_N', 'dest' : [ 'mipi_csi_isp_clk_rxn' ], 'cmt' : '', 'io':'LVCMOS18', 'func':'isp', 'pin':'F1' },
	'C5'			: 'GND',
        'C6'			: { 'net' : 'HPA03_P', 'dest' : [ 'mipi_csi_isp_data_rxp[2]' ], 'cmt' : '', 'io':'LVCMOS18', 'func':'isp' },
        'C7'			: { 'net' : 'HPA03_N', 'dest' : [ 'mipi_csi_isp_data_rxp[2]' ], 'cmt' : '', 'io':'LVCMOS18', 'func':'isp', 'pin':'F3' },
	'C8'			: 'GND',
        'C9'			: { 'net' : 'HPA08_P', 'dest' : [ 'mipi_csi_ias_data_rxp[2]' ], 'cmt' : '', 'func' : 'ias1', 'io':'LVCMOS18', 'pin':'B4' },
        'C10'			: { 'net' : 'HPA08_N', 'dest' : [ 'mipi_csi_ias_data_rxn[2]' ], 'cmt' : '', 'func' : 'ias1', 'io':'LVCMOS18', 'pin':'A4' },
	'C11'			: 'GND',
        'C12'			: { 'net' : 'HPA10_CC_P', 'dest' : [ 'rpi_clk_rxp' ], 'cmt' : '', 'func' : 'rpi', 'io':'LVCMOS18', 'pin':'D7' },
        'C13'			: { 'net' : 'HPA10_CC_N', 'dest' : [ 'rpi_clk_rxn' ], 'cmt' : '', 'func' : 'rpi', 'io':'LVCMOS18', 'pin':'D6' },
	'C14'			: 'GND',
	'C15'			: { 'net' : 'PS_POR_B', 'dest' : [ 'slg7xl44677_som_ps_por_b', 'ftdi_ps_por_b_ls' ], 'cmt' : '' },
	'C16'			: { 'net' : 'PS_SRST_C2M_B', 'dest' : [ 'ftdi_ps_srst_b_ls', 'j3_ps_srst_c2m_b', 'wdog_wdo_b' ], 'cmt' : 'soft reset by FTDI or WDOG (or JTAG?)' },
	'C17'			: 'GND',
        'C18'			: { 'net' : 'HDA06', 'dest' : [ ], 'cmt' : '', 'func' : 'nc', 'pin':'H11' },
        'C19'			: { 'net' : 'HDA07', 'dest' : [ ], 'cmt' : '', 'func' : 'nc', 'pin':'G10' },
        'C20'			: { 'net' : 'HDA08_CC', 'dest' : [ ], 'cmt' : '', 'func' : 'nc', 'pin':'F12' },
	'C21'			: 'GND',
        'C22'			: { 'net' : 'HDA18', 'dest' : [ 'pmod_8' ], 'v':3.3, 'cmt' : '', 'func': 'pmod', 'io':'LVCMOS33', 'pin':'B11' },
        'C23'			: { 'net' : 'HDA19', 'dest' : [ ], 'cmt' : '', 'func' : 'nc', 'pin':'A10' },
        'C24'			: { 'net' : 'HDA20', 'dest' : ['fan_en_b' ], 'cmt' : '', 'pin': 'A12', 'io':'LVCMOS33', 'v':3.3, 'func':'misc' },
	'C25'			: 'GND',
	'C26'			: { 'net' : 'I2C_SCK', 'dest' : ['' ], 'cmt' : '' },
	'C27'			: { 'net' : 'I2C_SDA', 'dest' : ['' ], 'cmt' : '' },
	'C28'			: { 'net' : 'FWUEN_C2M_B', 'dest' : ['' ], 'cmt' : '' },
	'C29'			: 'GND',
	'C30'			: { 'net' : 'MIO29', 'dest' : [ 'som_dp_oe_ls' ], 'v': 1.8, 'cmt' : 'DP AUX LVDS driver/receiver OE' },
	'C31'			: { 'net' : 'MIO30', 'dest' : [ 'som_dp_aux_in_ls' ], 'v': 1.8, 'cmt' : 'DP AUX single-ended input to SOM' },
	'C32'			: { 'net' : 'MIO31', 'dest' : [ 'shutdown' ], 'v': 1.8, 'cmt' : 'TP37' },
	'C33'			: 'GND',
        'C34'			: { 'net' : 'MIO47', 'dest' : [ 'sdio_dat1' ], 'v': 1.8, 'cmt' : '', 'func':'sdio' },
        'C35'			: { 'net' : 'MIO48', 'dest' : [ 'sdio_dat2' ], 'v': 1.8, 'cmt' : '', 'func':'sdio' },
        'C36'			: { 'net' : 'MIO49', 'dest' : [ 'sdio_dat3' ], 'v': 1.8, 'cmt' : '', 'func':'sdio' },
	'C37'			: 'GND',
        'C38'			: { 'net' : 'MIO55', 'dest' : [ 'ulpi_nxt' ], 'v': 1.8, 'cmt' : '', 'func':'ulpi' },
        'C39'			: { 'net' : 'MIO56', 'dest' : [ 'ulpi_data0' ], 'v': 1.8, 'cmt' : '', 'func':'ulpi' },
        'C40'			: { 'net' : 'MIO57', 'dest' : [ 'ulpi_data1' ], 'v': 1.8, 'cmt' : '', 'func':'ulpi' },
	'C41'			: 'GND',
        'C42'			: { 'net' : 'MIO67', 'dest' : [ 'eth_tx_d2' ], 'v': 1.8, 'cmt' : '', 'func':'eth' },
        'C43'			: { 'net' : 'MIO68', 'dest' : [ 'eth_tx_d3' ], 'v': 1.8, 'cmt' : '', 'func':'eth' },
        'C44'			: { 'net' : 'MIO69', 'dest' : [ 'eth_tx_ctrl' ], 'v': 1.8, 'cmt' : '', 'func':'eth' },
        'C45'			: { 'net' : 'SOM240_1_C45', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '', 'func' : 'nc' },
	'C46'			: 'GND',
	'C47'			: { 'net' : 'GTR_REFCLK0_C2M_P', 'dest' : [ 'clkgen_out5' ], 'v': 1.8, 'cmt' : '27MHz - Used by PS' },
	'C48'			: { 'net' : 'GTR_REFCLK0_C2M_N', 'dest' : [ 'clkgen_out5b' ], 'v': 1.8, 'cmt' : '27MHz - Used by PS' },
	'C49'			: 'GND',
	'C50'			: 'GND',
        'C51'			: { 'net' : 'GTR_DP3_M2C_P', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '', 'func' : 'nc' },
        'C52'			: { 'net' : 'GTR_DP3_M2C_N', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '', 'func' : 'nc' },
	'C53'			: 'GND',
	'C54'			: 'GND',
        'C55'			: { 'net' : 'GTR_DP1_C2M_P', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '', 'func' : 'nc' },
        'C56'			: { 'net' : 'GTR_DP1_C2M_N', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '', 'func' : 'nc' },
	'C57'			: 'GND',
	'C58'			: 'GND',
	'C59'			: 'SOM_5V0',
	'C60'			: 'SOM_5V0',

	'D1'			: 'PL_1V2',
	'D2'			: 'PL_1V2',
	'D3'			: 'GND',
        'D4'			: { 'net' : 'HPA02_P', 'dest' : [ 'mipi_csi_isp_data_rxp[1]' ], 'v': 1.8, 'cmt' : '', 'io':'LVCMOS18', 'func':'isp' },
        'D5'			: { 'net' : 'HPA02_N', 'dest' : [ 'mipi_csi_isp_data_rxn[1]' ], 'v': 1.8, 'cmt' : '', 'io':'LVCMOS18', 'func':'isp', 'pin':'E2' },
	'D6'			: 'GND',
        'D7'			: { 'net' : 'HPA01_P', 'dest' : [ 'mipi_csi_isp_data_rxp[0]' ], 'v': 1.8, 'cmt' : '', 'io':'LVCMOS18', 'func':'isp', 'pin':'E1' },
        'D8'			: { 'net' : 'HPA01_N', 'dest' : [ 'mipi_csi_isp_data_rxn[0]' ], 'v': 1.8, 'cmt' : '', 'io':'LVCMOS18', 'func':'isp' },
	'D9'			: 'GND',
        'D10'			: { 'net' : 'HPA09_P', 'dest' : [ 'mipi_csi_ias_data_rxp[3]' ], 'v': 1.8, 'cmt' : '', 'func' : 'ias1', 'io':'LVCMOS18', 'pin':'D4' },
        'D11'			: { 'net' : 'HPA09_N', 'dest' : [ 'mipi_csi_ias_data_rxp[3]' ], 'v': 1.8, 'cmt' : '', 'func' : 'ias1', 'io':'LVCMOS18', 'pin':'C4' },
	'D12'			: 'GND',
        'D13'			: { 'net' : 'HPA14_P', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '', 'func' : 'nc', 'io':'LVCMOS18', 'pin':'F8' },
        'D14'			: { 'net' : 'HPA14_N', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '', 'func' : 'nc', 'io':'LVCMOS18', 'pin':'E8' },
	'D15'			: 'GND',
        'D16'			: { 'net' : 'HDA00_CC', 'dest' : [ 'hda_i2c_scl' ], 'v': 3.3, 'cmt' : 'HDA I2C switch between ISP, IAS1, RPI', 'pin':'G11', 'io':'LVCMOS33', 'func':'i2c' },
        'D17'			: { 'net' : 'HDA01', 'dest' : [ 'hda_i2c_sda' ], 'v': 3.3, 'cmt' : 'HDA I2C switch between ISP, IAS1, RPI', 'pin':'F10', 'io':'LVCMOS33', 'func':'i2c' },
        'D18'			: { 'net' : 'HDA02', 'dest' : [ 'ap1302_rst_b' ], 'v': 3.3, 'cmt' : '', 'pin': 'J11', 'io': 'lvcmos33', 'func':'isp', 'io':'LVCMOS33' },
	'D19'			: 'GND',
        'D20'			: { 'net' : 'HDA12', 'dest' : [ 'pmod_3' ], 'v': 3.3, 'cmt' : '', 'io':'LVCMOS33', 'func':'pmod', 'pin':'E10' },
        'D21'			: { 'net' : 'HDA13', 'dest' : [ 'pmod_5' ], 'v': 3.3, 'cmt' : '', 'io':'LVCMOS33', 'func':'pmod', 'pin':'D10' },
        'D22'			: { 'net' : 'HDA14', 'dest' : [ 'pmod_7' ], 'v': 3.3, 'cmt' : '', 'io':'LVCMOS33', 'func':'pmod', 'pin':'C11' },
	'D23'			: 'GND',
	'D24'			: { 'net' : 'PWRGD_FPD_M2C', 'dest' : [ '' ], 'v': 1.8, 'cmt' : 'PWR LED' },
	'D25'			: { 'net' : 'PWRGD_LPD_M2C', 'dest' : [ '' ], 'v': 1.8, 'cmt' : 'PWR LED' },
	'D26'			: { 'net' : 'PWRGD_PL_M2C', 'dest' : [ '' ], 'v': 1.8, 'cmt' : 'PWR LED' },
	'D27'			: 'GND',
	'D28'			: { 'net' : 'MIO26', 'dest' : [ 'watchdog_wdo_b' ], 'v': 1.8, 'cmt' : 'WDOG feedback back to PS?' },
	'D29'			: { 'net' : 'MIO27', 'dest' : [ 'som_dp_uax_out_ls' ], 'v': 1.8, 'cmt' : 'Single-ended DPAUX from module to LVDS' },
	'D30'			: { 'net' : 'MIO28', 'dest' : [ 'som_dp_hpd_ls' ], 'v': 1.8, 'cmt' : '' },
	'D31'			: 'GND',
	'D32'			: { 'net' : 'MIO44', 'dest' : [ 'slg7xl44677_ps_mio_usb_hub' ], 'v': 1.8, 'cmt' : '' },
        'D33'			: { 'net' : 'MIO45', 'dest' : [ 'sdio_detect' ], 'v': 1.8, 'cmt' : '', 'func':'sdio' },
        'D34'			: { 'net' : 'MIO46', 'dest' : [ 'sdio_dat0' ], 'v': 1.8, 'cmt' : '', 'func':'sdio' },
	'D35'			: 'GND',
        'D36'			: { 'net' : 'MIO52', 'dest' : [ 'ulpi_clk' ], 'v': 1.8, 'cmt' : '', 'func':'ulpi' },
        'D37'			: { 'net' : 'MIO53', 'dest' : [ 'ulpi_dir' ], 'v': 1.8, 'cmt' : '', 'func':'ulpi' },
        'D38'			: { 'net' : 'MIO54', 'dest' : [ 'ulpi_data2' ], 'v': 1.8, 'cmt' : '', 'func':'ulpi' },
	'D39'			: 'GND',
        'D40'			: { 'net' : 'MIO64', 'dest' : [ 'eth_gtx_clk' ], 'v': 1.8, 'cmt' : '', 'func':'eth' },
        'D41'			: { 'net' : 'MIO65', 'dest' : [ 'eth_tx_d0' ], 'v': 1.8, 'cmt' : '', 'func':'eth' },
        'D42'			: { 'net' : 'MIO66', 'dest' : [ 'eth_tx_d1' ], 'v': 1.8, 'cmt' : '', 'func':'eth' },
	'D43'			: 'GND',
        'D44'			: { 'net' : 'MIO76', 'dest' : [ 'eth_mdc' ], 'v': 1.8, 'cmt' : '', 'func':'eth' },
        'D45'			: { 'net' : 'MIO77', 'dest' : [ 'eth_mdio' ], 'v': 1.8, 'cmt' : '', 'func':'eth' },
        'D46'			: { 'net' : 'SOM240_1_D46', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '', 'func' : 'nc' },
	'D47'			: 'GND',
	'D48'			: 'GND',
        'D49'			: { 'net' : 'GTR_DP3_C2M_P', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '', 'func' : 'nc' },
        'D50'			: { 'net' : 'GTR_DP3_C2M_N', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '', 'func' : 'nc' },
	'D51'			: 'GND',
	'D52'			: 'GND',
	'D53'			: { 'net' : 'GTR_REFCLK2_C2M_P', 'dest' : [ 'clkgen_out0' ], 'v': 1.8, 'cmt' : '125MHz - Goes to PS' },
	'D54'			: { 'net' : 'GTR_REFCLK2_C2M_N', 'dest' : [ 'clkgen_out0b' ], 'v': 1.8, 'cmt' : '125MHz - Goes to PS' },
	'D55'			: 'GND',
	'D56'			: 'GND',
	'D57'			: { 'net' : 'GTR_DP2_M2C_P', 'dest' : [ 'usb3up_rxdp' ], 'v': 1.8, 'cmt' : '' },
	'D58'			: { 'net' : 'GTR_DP2_M2C_N', 'dest' : [ 'usb3up_rxdm' ], 'v': 1.8, 'cmt' : '' },
	'D59'			: 'GND',
	'D60'			: 'SOM_5V0',

	
}
