
som240_1_pins = {

	'A1'			: 'vcc_batt',
	'A2'			: 'gnd',
	'A3'			: { 'net' : 'HPA06_P', 'dest' : [ 'ias1_4' ] },
	'A4'			: { 'net' : 'HPA06_N', 'dest' : [ 'ias1_5' ] },
	'A5'			: 'gnd',
	'A6'			: { 'net' : 'HPA_CLK0_P_NC', 'dest' : [ ] },
	'A7'			: { 'net' : 'HPA_CLK0_P_NC', 'dest' : [ ] },
	'A8'			: 'gnd',
	'A9'			: { 'net' : 'HPA12_P', 'dest' : [ 'rasp_6' ] },
	'A10'			: { 'net' : 'HPA12_N', 'dest' : [ 'rasp_5' ] },
	'A11'			: 'gnd',
	'A12'			: { 'net' : 'HPA13_P_NC', 'dest' : [  ] },
	'A13'			: { 'net' : 'HPA13_N_NC', 'dest' : [  ] },
	'A14'			: 'gnd',
	'A15'			: { 'net' : 'HDA09', 'dest' : [ 'slg7x44677_hdio_rpi' ], 'cmt': 'reset controller?'  },
	'A16'			: { 'net' : 'HDA10', 'dest' : [ 'rasp_12' ] },
	'A17'			: { 'net' : 'HDA11', 'dest' : [ 'pmod_1' ] },
	'A18'			: 'gnd',
	'A19'			: { 'net' : 'VCCOEN_PS_M2C', 'dest' : [  ], 'cmt' : 'PS_1V2, PS_1V8, and PS_3V3 regulator enable.' },
	'A20'			: { 'net' : 'VCCOEN_PL_M2C', 'dest' : [  ], 'cmt' : 'PL_1V2, PL_1V8, and PL_3V3 regulator enable.' },
	'A21'			: 'gnd',
	'A22'			: { 'net' : 'JTAG_TMS_C2M', 'dest' : [ 'ftdi_tms', 'j3_tms' ], 'v': 1.8, 'cmt' : '' },
	'A23'			: { 'net' : 'JTAG_TDO_M2C', 'dest' : [ 'ftdi_tdo', 'j3_tdo' ], 'v': 1.8, 'cmt' : '' },
	'A24'			: { 'net' : 'JTAG_TDI_C2M', 'dest' : [ 'ftdi_tdi', 'j3_tdi' ], 'v': 1.8, 'cmt' : '' },
	'A25'			: { 'net' : 'JTAG_TCK_C2M', 'dest' : [ 'ftdi_tck', 'j3_tck' ], 'v': 1.8, 'cmt' : '' },
	'A26'			: 'gnd',
	'A27'			: { 'net' : 'MODE0_C2M', 'dest' : [ 'gnd' ], 'cmt' : '' },
	'A28'			: { 'net' : 'MODE1_C2M', 'dest' : [ ], 'cmt' : 'Probably a pullup on the module' },
	'A29'			: { 'net' : 'MODE2_C2M', 'dest' : [ 'gnd' ], 'cmt' : '' },
	'A30'			: { 'net' : 'MODE3_C2M', 'dest' : [ 'gnd' ], 'cmt' : '' },
	'A31'			: { 'net' : 'MIO32_NC', 'dest' : [  ], 'cmt' : '' },
	'A32'			: { 'net' : 'MIO33_NC', 'dest' : [  ], 'cmt' : '' },
	'A33'			: 'gnd',
	'A34'			: { 'net' : 'MIO41_NC', 'dest' : [  ], 'cmt' : '' },
	'A35'			: { 'net' : 'MIO42_NC', 'dest' : [  ], 'cmt' : '' },
	'A36'			: { 'net' : 'MIO43', 'dest' : [ 'slg7x44677_ps_mio_sd' ], 'cmt' : '' },
	'A37'			: 'gnd',
	'A38'			: { 'net' : 'MIO61', 'dest' : [ 'ulpi_data5' ], 'v': 1.8, 'cmt' : '' },
	'A39'			: { 'net' : 'MIO62', 'dest' : [ 'ulpi_data6' ], 'v': 1.8, 'cmt' : '' },
	'A40'			: { 'net' : 'MIO63', 'dest' : [ 'ulpi_data7' ], 'v': 1.8, 'cmt' : '' },
	'A41'			: 'gnd',
	'A42'			: { 'net' : 'MIO73', 'dest' : [ 'eth_rx_d2' ], 'v': 1.8 , 'cmt' : '' },
	'A43'			: { 'net' : 'MIO74', 'dest' : [ 'eth_rx_d3' ], 'v': 1.8 , 'cmt' : '' },
	'A44'			: { 'net' : 'MIO75', 'dest' : [ 'eth_rx_ctrl' ], 'v': 1.8 , 'cmt' : '' },
	'A45'			: 'gnd',
	'A46'			: 'gnd',
	'A47'			: { 'net' : 'GTR_DP1_M2C_P', 'dest' : [ 'stdp4320_rx0_ln0_p' ], 'cmt' : 'DP out' },
	'A48'			: { 'net' : 'GTR_DP1_M2C_N', 'dest' : [ 'stdp4320_rx0_ln0_n' ], 'cmt' : 'DP out' },
	'A49'			: 'gnd',
	'A50'			: 'gnd',
	'A51'			: { 'net' : 'GTR_REFCLK3_C2M_P_NC', 'dest' : [ '' ], 'cmt' : '' },
	'A52'			: { 'net' : 'GTR_REFCLK3_C2M_N_NC', 'dest' : [ '' ], 'cmt' : '' },
	'A53'			: 'gnd',
	'A54'			: 'gnd',
	'A55'			: { 'net' : 'GTR_DP0_C2M_P_NC', 'dest' : [ '' ], 'cmt' : 'DP in ' },
	'A56'			: { 'net' : 'GTR_DP0_C2M_N_NC', 'dest' : [ '' ], 'cmt' : 'DP in ' },
	'A57'			: 'gnd',
	'A58'			: 'gnd',
	'A59'			: 'SOM_5V0',
	'A60'			: 'SOM_5V0',

	'B1'			:  { 'net' : 'HPA05_CC_P', 'dest' : [ 'ias1_7' ], 'cmt' : '' },
	'B2'			:  { 'net' : 'HPA05_CC_N', 'dest' : [ 'ias1_8' ], 'cmt' : '' },
	'B3'			: 'gnd',
	'B4'			:  { 'net' : 'HPA04_P', 'dest' : [ 'ap1302_h_d3_dp' ], 'cmt' : '' },
	'B5'			:  { 'net' : 'HPA04_N', 'dest' : [ 'ap1302_h_d3_dn' ], 'cmt' : '' },
	'B6'			: 'gnd',
	'B7'			:  { 'net' : 'HPA07_P', 'dest' : [ 'ias1_30' ], 'cmt' : '' },
	'B8'			:  { 'net' : 'HPA07_N', 'dest' : [ 'ias1_29' ], 'cmt' : '' },
	'B9'			: 'gnd',
	'B10'			:  { 'net' : 'HPA11_P', 'dest' : [ 'rasp_3' ], 'cmt' : '' },
	'B11'			:  { 'net' : 'HPA11_N', 'dest' : [ 'rasp_2' ], 'cmt' : '' },
	'B12'			: 'gnd',
	'B13'			: 'PL_3V3',
	'B14'			: 'PL_3V3',
	'B15'			: 'gnd',
	'B16'			:  { 'net' : 'HDA03', 'dest' : [ 'ap1302_standby' ], 'cmt' : '' },
	'B17'			:  { 'net' : 'HDA04', 'dest' : [ 'slg7xl44677_hdio_direct' ], 'cmt' : '' },
	'B18'			:  { 'net' : 'HDA05_NC', 'dest' : [ '' ], 'cmt' : '' },
	'B19'			: 'gnd',
	'B20'			:  { 'net' : 'HDA15', 'dest' : [ 'pmod_2' ], 'cmt' : '' },
	'B21'			:  { 'net' : 'HDA16_CC', 'dest' : [ 'pmod_4' ], 'cmt' : '' },
	'B22'			:  { 'net' : 'HDA17', 'dest' : [ 'pmod_6' ], 'cmt' : '' },
	'B23'			: 'gnd',
	'B24'			:  { 'net' : 'PS_ERROR_OUT_M2C', 'dest' : [ 'tp38' ], 'cmt' : '' },
	'B25'			:  { 'net' : 'PS_ERROR_STATUS_M2C', 'dest' : [ 'tp39' ], 'cmt' : '' },
	'B26'			:  { 'net' : 'PWROFF_C2M_B', 'dest' : [ '' ], 'cmt' : 'comes from 12DC barrel jack plug detect, goes to regulators Power Good' },
	'B27'			: 'gnd',
	'B28'			: { 'net' : 'MIO35', 'dest' : [ 'wdog_wdi' ], 'v': 1.8, 'cmt' : '' },
	'B29'			: { 'net' : 'MIO36', 'dest' : [ 'som_uart1_txd' ], 'v': 1.8, 'cmt' : '' },
	'B30'			: { 'net' : 'MIO37', 'dest' : [ 'som_uart2_rxd' ], 'v': 1.8, 'cmt' : '' },
	'B31'			: 'gnd',
	'B32'			: { 'net' : 'MIO38', 'dest' : [ 'slg7xl44677_ps_mio_eth' ], 'v': 1.8, 'cmt' : '' },
	'B33'			: { 'net' : 'MIO39', 'dest' : [ 'sdio_sel' ], 'v': 1.8, 'cmt' : 'activates level shifter pi4uls3v4857' },
	'B34'			: { 'net' : 'MIO40_NC', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '' },
	'B35'			: 'gnd',
	'B36'			: { 'net' : 'MIO50', 'dest' : [ 'sdio_cmd' ], 'v': 1.8, 'cmt' : '' },
	'B37'			: { 'net' : 'MIO51', 'dest' : [ 'sdio_clk' ], 'v': 1.8, 'cmt' : '' },
	'B38'			: { 'net' : 'MIO34_NC', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '' },
	'B39'			: 'gnd',
	'B40'			: { 'net' : 'MIO58', 'dest' : [ 'ulpi_stp' ], 'v': 1.8, 'cmt' : '' },
	'B41'			: { 'net' : 'MIO59', 'dest' : [ 'ulpi_data3' ], 'v': 1.8, 'cmt' : '' },
	'B42'			: { 'net' : 'MIO60', 'dest' : [ 'ulpi_data4' ], 'v': 1.8, 'cmt' : '' },
	'B43'			: 'gnd',
	'B44'			: { 'net' : 'MIO70', 'dest' : [ 'eth_rx_clk' ], 'v': 1.8, 'cmt' : '' },
	'B45'			: { 'net' : 'MIO71', 'dest' : [ 'eth_rx_d0' ], 'v': 1.8, 'cmt' : '' },
	'B46'			: { 'net' : 'MIO72', 'dest' : [ 'eth_rx_d1' ], 'v': 1.8, 'cmt' : '' },
	'B47'			: 'gnd',
	'B48'			: 'gnd',
	'B49'			: { 'net' : 'GTR_REFCLK1_C2M_P', 'dest' : [ 'clkgen_out4' ], 'cmt' : 'Si5332 - 26MHz - Used by PS' },
	'B50'			: { 'net' : 'GTR_REFCLK1_C2M_N', 'dest' : [ 'clkgen_out4b' ], 'cmt' : 'Si5332 - 26MHz - Used by PS' },
	'B51'			: 'gnd',
	'B52'			: 'gnd',
	'B53'			: { 'net' : 'GTR_DP2_C2M_P', 'dest' : [ 'usb5744_usb3up_txdp' ], 'cmt' : 'upstream facing usb3 port of hub' },
	'B54'			: { 'net' : 'GTR_DP2_C2M_N', 'dest' : [ 'usb5744_usb3up_txdm' ], 'cmt' : 'upstream facing usb3 port of hub' },
	'B55'			: 'gnd',
	'B56'			: 'gnd',
	'B57'			: { 'net' : 'GTR_DP0_M2C_P', 'dest' : [ 'stdp4320_rx0_ln1_p' ], 'cmt' : '' },
	'B58'			: { 'net' : 'GTR_DP0_M2C_N', 'dest' : [ 'stdp4320_rx0_ln1_n' ], 'cmt' : '' },
	'B59'			: 'gnd',
	'B60'			: 'SOM_5V0',

	'C1'			: 'gnd',
	'C2'			: 'gnd',
	'C3'			: { 'net' : 'HPA00_CC_P', 'dest' : [ 'ap1302_h_clk_dp' ], 'cmt' : '' },
	'C4'			: { 'net' : 'HPA00_CC_N', 'dest' : [ 'ap1302_h_clk_dn' ], 'cmt' : '' },
	'C5'			: 'gnd',
	'C6'			: { 'net' : 'HPA03_P', 'dest' : [ 'ap1302_h_d2_dp' ], 'cmt' : '' },
	'C7'			: { 'net' : 'HPA03_N', 'dest' : [ 'ap1302_h_d2_dn' ], 'cmt' : '' },
	'C8'			: 'gnd',
	'C9'			: { 'net' : 'HPA08_P', 'dest' : [ 'ias1_27' ], 'cmt' : '' },
	'C10'			: { 'net' : 'HPA08_N', 'dest' : [ 'ias1_26' ], 'cmt' : '' },
	'C11'			: 'gnd',
	'C12'			: { 'net' : 'HPA10_CC_P', 'dest' : [ 'rasp_9' ], 'cmt' : '' },
	'C13'			: { 'net' : 'HPA10_CC_N', 'dest' : [ 'rasp_8' ], 'cmt' : '' },
	'C14'			: 'gnd',
	'C15'			: { 'net' : 'PS_POR_B', 'dest' : [ 'slg7xl44677_som_ps_por_b', 'ftdi_ps_por_b_ls' ], 'cmt' : '' },
	'C16'			: { 'net' : 'PS_SRST_C2M_B', 'dest' : [ 'ftdi_ps_srst_b_ls', 'j3_ps_srst_c2m_b', 'wdog_wdo_b' ], 'cmt' : 'soft reset by FTDI or WDOG (or JTAG?)' },
	'C17'			: 'gnd',
	'C18'			: { 'net' : 'HDA06_NC', 'dest' : [ ], 'cmt' : '' },
	'C19'			: { 'net' : 'HDA07_NC', 'dest' : [ ], 'cmt' : '' },
	'C20'			: { 'net' : 'HDA08_CC_NC', 'dest' : [ ], 'cmt' : '' },
	'C21'			: 'gnd',
	'C22'			: { 'net' : 'HDA18', 'dest' : [ 'pmod_8' ], 'cmt' : '' },
	'C23'			: { 'net' : 'HDA19_NC', 'dest' : [ ], 'cmt' : '' },
	'C24'			: { 'net' : 'HDA20', 'dest' : ['fan' ], 'cmt' : '' },
	'C25'			: 'gnd',
	'C26'			: { 'net' : 'I2C_SCK', 'dest' : ['' ], 'cmt' : '' },
	'C27'			: { 'net' : 'I2C_SDA', 'dest' : ['' ], 'cmt' : '' },
	'C28'			: { 'net' : 'FWUEN_C2M_B', 'dest' : ['' ], 'cmt' : '' },
	'C29'			: 'gnd',
	'C30'			: { 'net' : 'MIO29', 'dest' : [ 'som_dp_oe_ls' ], 'v': 1.8, 'cmt' : 'DP AUX LVDS driver/receiver OE' },
	'C31'			: { 'net' : 'MIO30', 'dest' : [ 'som_dp_aux_in_ls' ], 'v': 1.8, 'cmt' : 'DP AUX single-ended input to SOM' },
	'C32'			: { 'net' : 'MIO31', 'dest' : [ 'shutdown' ], 'v': 1.8, 'cmt' : 'TP37' },
	'C33'			: 'gnd',
	'C34'			: { 'net' : 'MIO47', 'dest' : [ 'sdio_dat1' ], 'v': 1.8, 'cmt' : '' },
	'C35'			: { 'net' : 'MIO48', 'dest' : [ 'sdio_dat2' ], 'v': 1.8, 'cmt' : '' },
	'C36'			: { 'net' : 'MIO49', 'dest' : [ 'sdio_dat3' ], 'v': 1.8, 'cmt' : '' },
	'C37'			: 'gnd',
	'C38'			: { 'net' : 'MIO55', 'dest' : [ 'ulpi_nxt' ], 'v': 1.8, 'cmt' : '' },
	'C39'			: { 'net' : 'MIO56', 'dest' : [ 'ulpi_data0' ], 'v': 1.8, 'cmt' : '' },
	'C40'			: { 'net' : 'MIO57', 'dest' : [ 'ulpi_data1' ], 'v': 1.8, 'cmt' : '' },
	'C41'			: 'gnd',
	'C42'			: { 'net' : 'MIO67', 'dest' : [ 'eth_tx_d2' ], 'v': 1.8, 'cmt' : '' },
	'C43'			: { 'net' : 'MIO68', 'dest' : [ 'eth_tx_d3' ], 'v': 1.8, 'cmt' : '' },
	'C44'			: { 'net' : 'MIO69', 'dest' : [ 'eth_tx_ctrl' ], 'v': 1.8, 'cmt' : '' },
	'C45'			: { 'net' : 'SOM240_1_C45_NC', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '' },
	'C46'			: 'gnd',
	'C47'			: { 'net' : 'GTR_REFCLK0_C2M_P', 'dest' : [ 'clkgen_out5' ], 'v': 1.8, 'cmt' : '27MHz - Used by PS' },
	'C48'			: { 'net' : 'GTR_REFCLK0_C2M_N', 'dest' : [ 'clkgen_out5b' ], 'v': 1.8, 'cmt' : '27MHz - Used by PS' },
	'C49'			: 'gnd',
	'C50'			: 'gnd',
	'C51'			: { 'net' : 'GTR_DP3_M2C_P_NC', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '' },
	'C52'			: { 'net' : 'GTR_DP3_M2C_N_NC', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '' },
	'C53'			: 'gnd',
	'C54'			: 'gnd',
	'C55'			: { 'net' : 'GTR_DP1_C2M_P_NC', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '' },
	'C56'			: { 'net' : 'GTR_DP1_C2M_N_NC', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '' },
	'C57'			: 'gnd',
	'C58'			: 'gnd',
	'C59'			: 'SOM_5V0',
	'C60'			: 'SOM_5V0',

	'D1'			: 'PL_1V2',
	'D2'			: 'PL_1V2',
	'D3'			: 'gnd',
	'D4'			: { 'net' : 'HPA02_P', 'dest' : [ 'ap1302_h_d1_dp' ], 'v': 1.8, 'cmt' : '' },
	'D5'			: { 'net' : 'HPA02_N', 'dest' : [ 'ap1302_h_d1_dn' ], 'v': 1.8, 'cmt' : '' },
	'D6'			: 'gnd',
	'D7'			: { 'net' : 'HPA01_P', 'dest' : [ 'ap1302_h_d0_dp' ], 'v': 1.8, 'cmt' : '' },
	'D8'			: { 'net' : 'HPA01_N', 'dest' : [ 'ap1302_h_d0_dn' ], 'v': 1.8, 'cmt' : '' },
	'D9'			: 'gnd',
	'D10'			: { 'net' : 'HPA09_P', 'dest' : [ 'ias1_10' ], 'v': 1.8, 'cmt' : '' },
	'D11'			: { 'net' : 'HPA09_N', 'dest' : [ 'ias1_11' ], 'v': 1.8, 'cmt' : '' },
	'D12'			: 'gnd',
	'D13'			: { 'net' : 'HPA14_P_NC', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '' },
	'D14'			: { 'net' : 'HPA14_N_NC', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '' },
	'D15'			: 'gnd',
	'D16'			: { 'net' : 'HDA00_CC', 'dest' : [ 'hda_i2c_scl' ], 'v': 1.8, 'cmt' : 'HDA I2C switch between ISP, IAS1, RPI' },
	'D17'			: { 'net' : 'HDA01', 'dest' : [ 'hda_i2c_sda' ], 'v': 1.8, 'cmt' : 'HDA I2C switch between ISP, IAS1, RPI' },
	'D18'			: { 'net' : 'HDA02', 'dest' : [ 'slg7xl44677_hdio_isp' ], 'v': 1.8, 'cmt' : '' },
	'D19'			: 'gnd',
	'D20'			: { 'net' : 'HDA12', 'dest' : [ 'pmod3' ], 'v': 1.8, 'cmt' : '' },
	'D21'			: { 'net' : 'HDA13', 'dest' : [ 'pmod5' ], 'v': 1.8, 'cmt' : '' },
	'D22'			: { 'net' : 'HDA14', 'dest' : [ 'pmod7' ], 'v': 1.8, 'cmt' : '' },
	'D23'			: 'gnd',
	'D24'			: { 'net' : 'PWRGD_FPD_M2C', 'dest' : [ '' ], 'v': 1.8, 'cmt' : PWR LED'' },
	'D25'			: { 'net' : 'PWRGD_LPD_M2C', 'dest' : [ '' ], 'v': 1.8, 'cmt' : 'PWR LED' },
	'D26'			: { 'net' : 'PWRGD_PL_M2C', 'dest' : [ '' ], 'v': 1.8, 'cmt' : 'PWR LED' },
	'D27'			: 'gnd',
	'D28'			: { 'net' : 'MIO26', 'dest' : [ 'watchdog_wdo_b' ], 'v': 1.8, 'cmt' : 'WDOG feedback back to PS?' },
	'D29'			: { 'net' : 'MIO27', 'dest' : [ 'som_dp_uax_out_ls' ], 'v': 1.8, 'cmt' : 'Single-ended DPAUX from module to LVDS' },
	'D30'			: { 'net' : 'MIO28', 'dest' : [ 'som_dp_hpd_ls' ], 'v': 1.8, 'cmt' : '' },
	'D31'			: 'gnd',
	'D32'			: { 'net' : 'MIO44', 'dest' : [ 'slg7xl44677_ps_mio_usb_hub' ], 'v': 1.8, 'cmt' : '' },
	'D33'			: { 'net' : 'MIO45', 'dest' : [ 'sdio_detect' ], 'v': 1.8, 'cmt' : '' },
	'D34'			: { 'net' : 'MIO46', 'dest' : [ 'sdio_dat0' ], 'v': 1.8, 'cmt' : '' },
	'D35'			: 'gnd',
	'D36'			: { 'net' : 'MIO52', 'dest' : [ 'ulpi_clk' ], 'v': 1.8, 'cmt' : '' },
	'D37'			: { 'net' : 'MIO53', 'dest' : [ 'ulpi_dir' ], 'v': 1.8, 'cmt' : '' },
	'D38'			: { 'net' : 'MIO54', 'dest' : [ 'ulpi_data2' ], 'v': 1.8, 'cmt' : '' },
	'D39'			: 'gnd',
	'D40'			: { 'net' : 'MIO64', 'dest' : [ 'eth_gtx_clk' ], 'v': 1.8, 'cmt' : '' },
	'D41'			: { 'net' : 'MIO65', 'dest' : [ 'eth_tx_d0' ], 'v': 1.8, 'cmt' : '' },
	'D42'			: { 'net' : 'MIO66', 'dest' : [ 'eth_tx_d1' ], 'v': 1.8, 'cmt' : '' },
	'D43'			: 'gnd',
	'D44'			: { 'net' : 'MIO76', 'dest' : [ 'eth_mdc' ], 'v': 1.8, 'cmt' : '' },
	'D45'			: { 'net' : 'MIO77', 'dest' : [ 'eth_mdio' ], 'v': 1.8, 'cmt' : '' },
	'D46'			: { 'net' : 'SOM240_1_D46_NC', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '' },
	'D47'			: 'gnd',
	'D48'			: 'gnd',
	'D49'			: { 'net' : 'GTR_DP3_C2M_P_NC', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '' },
	'D50'			: { 'net' : 'GTR_DP3_C2M_N_NC', 'dest' : [ '' ], 'v': 1.8, 'cmt' : '' },
	'D51'			: 'gnd',
	'D52'			: 'gnd',
	'D53'			: { 'net' : 'GTR_REFCLK2_C2M_P', 'dest' : [ 'clkgen_out0' ], 'v': 1.8, 'cmt' : '125MHz - Goes to PS' },
	'D54'			: { 'net' : 'GTR_REFCLK2_C2M_N', 'dest' : [ 'clkgen_out0b' ], 'v': 1.8, 'cmt' : '125MHz - Goes to PS' },
	'D55'			: 'gnd',
	'D56'			: 'gnd',
	'D57'			: { 'net' : 'GTR_DP2_M2C_P', 'dest' : [ 'usb3up_rxdp' ], 'v': 1.8, 'cmt' : '' },
	'D58'			: { 'net' : 'GTR_DP2_M2C_N', 'dest' : [ 'usb3up_rxdm' ], 'v': 1.8, 'cmt' : '' },
	'D59'			: 'gnd',
	'D60'			: 'SOM_5V0',

	
}
